### ISSUE TITLE
Correction on regulator trace.

### ISSUE THREAD

**Issue by joksan** [Upcycle-Electronics/game-and-watch-hardware#1]
Hello!

First of all, thank you for this amazing effort of reverse engineering the Game And Watch. It's been incredibly useful to me and I'm sure to others as well.

I just wanted to kindly point out an error I discovered in the colored trace images (GnWtrace1v0.png and others). In the 1.8V regulator area there's this SDM component that is an inductor in a 2016 package (it's right besides the M-1 label). Both ends of the inductor are colored the same, which suggests that they're joined together. I'm afraid those are different traces, as they show very different signals in an oscilloscope. This inductor is part of the buck converter circuit and has the output switch at the end that leads to the regulator IC and the actual power output going to the rest of the circuit at the other end.

I hope you find this little bit of information useful. Have a nice day!

**Comment by Upcycle-Electronics** [comment]
I should have thought of that. Continuity isn't always continuity. I'll ty and push a change tomorrow. 

  I guess this means that little stub of a trace on the left side of IC4 must be where the diode is hidden. Either that or I'm totally clueless about this switching topology. Both are equally possible. I really wish I could find out the chip used.
Thanks for letting me know.

**Comment by Upcycle-Electronics** [comment]
I think I fixed it. Thanks again.
![Version 1.1](https://raw.githubusercontent.com/Upcycle-Electronics/game-and-watch-hardware/main/Images-Version-1v1/GnWtrace1v1.jpg "Version 1.1")

**Comment by joksan** [comment]
Yay! thanks!

I'm fairly certain that both the diode and the output switch are included inside the voltage regulator. That stub trace you mention is most probably the output voltage feedback for the regulator.
