### ISSUE TITLE
I came to help.

### ISSUE THREAD

**Issue by miraclehoshi** [Upcycle-Electronics/game-and-watch-hardware#2]
I noticed that you are not yet in Discord dealing with game and watch hacks.

Except for the power switch parts, all parts were found with the help of me and several people.

Type-C Connector : JAE DX07BN24JA2R1300
1.9V Reg : dialog semiconductor DA9230
3.3V Reg : STMicroelectronics LD39020DTPU33R
Audio Amplifier : nuvoton NAU8315

If you are interested, how about joining Discord?
https://discord.gg/P7uPM3Sy

**Comment by Upcycle-Electronics** [comment]
Alright. I'll set up an account when I get back on a computer tomorrow. Thanks for the info. 
Do you know the power button and crystal part number?  *(edit...stupid me..."except for the power switch parts"...sry)
  Also, sources?
I searched:
smdmark.com (where I got the MOSFET pn from)
smd.yooneed.one
alltransistor.com
octopart
digikey, mouser, arrow, newark, ti, torex, lcsc, aliex
...so far. It seems you have sources and techniques I'd like to know and get familiar with.

**Comment by miraclehoshi** [comment]
Crystal is a common standard, so I couldn't think of finding it. Let's try.
The sources of other parts were found by searching several sites. I was able to find it with various help.
I only used digikey and mouser.

The power switch part has been around for a long time on Nintendo, but I haven't been able to find the exact part yet. Considering that the genuine switch has not been found while at least three Copied parts have been released in China, it may be a special ordered part from Nintendo.

**Comment by Upcycle-Electronics** [comment]
Thanks for the help and info. Discord is not a good fit for me. Tracking down everything they are doing in the background is too much of a side project for a dumb guy like myself. Let me know if you guys move to something open source and privacy aware. I prefer a written messaging system anyways

  I wish the DA9230 wasn't made of unobtainium. That was the most interesting chip in the whole device. At least the pull down resistors to disable the I2C lines finally make sense.
If you read the documentation for the 9230 demo board they list a Murata inductor that is probably the one used on the GnW. At least it's the right odd footprint.

**Comment by Upcycle-Electronics** [comment]
Thanks again. The schematic has been updated.
